ddr_pin addrcmd_2t {SDRAM_A[0]} pins
ddr_pin addrcmd_2t {SDRAM_A[10]} pins
ddr_pin addrcmd_2t {SDRAM_A[11]} pins
ddr_pin addrcmd_2t {SDRAM_A[12]} pins
ddr_pin addrcmd_2t {SDRAM_A[13]} pins
ddr_pin addrcmd_2t {SDRAM_A[1]} pins
ddr_pin addrcmd_2t {SDRAM_A[2]} pins
ddr_pin addrcmd_2t {SDRAM_A[3]} pins
ddr_pin addrcmd_2t {SDRAM_A[4]} pins
ddr_pin addrcmd_2t {SDRAM_A[5]} pins
ddr_pin addrcmd_2t {SDRAM_A[6]} pins
ddr_pin addrcmd_2t {SDRAM_A[7]} pins
ddr_pin addrcmd_2t {SDRAM_A[8]} pins
ddr_pin addrcmd_2t {SDRAM_A[9]} pins
ddr_pin addrcmd_2t {SDRAM_BA[0]} pins
ddr_pin addrcmd_2t {SDRAM_BA[1]} pins
ddr_pin addrcmd_2t {SDRAM_BA[2]} pins
ddr_pin addrcmd_2t SDRAM_CASb pins
ddr_pin addrcmd_2t SDRAM_RASb pins
ddr_pin addrcmd_2t SDRAM_WEb pins
ddr_pin ck_p SDRAM_CK pins
ddr_pin dqsgroup {SDRAM_DQS SDRAM_DM {{SDRAM_DQ[0]} {SDRAM_DQ[1]} {SDRAM_DQ[2]} {SDRAM_DQ[3]} {SDRAM_DQ[4]} {SDRAM_DQ[5]} {SDRAM_DQ[6]} {SDRAM_DQ[7]}} {}} pins
ddr_pin ck_n SDRAM_CKb pins
ddr_pin addrcmd SDRAM_CKE pins
ddr_pin addrcmd SDRAM_ODT pins
ddr_pin addrcmd SDRAM_CSb pins
